apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backupdir-graphdb-neo4j-core-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ibmc-file-gold
