apiVersion: v1
kind: Pod
metadata:
  name: neo4j-restore-backup
spec:
  restartPolicy: Never
  containers:
    - name: neo4j-restore-backup
      image: neo4j:4.0.4-enterprise
      env:
      - name: BACKUP_DATABASE
        value: "neo4j"
      command:
      - "/bin/bash"
      - "-c"
      - "neo4j-admin restore --database=$BACKUP_DATABASE --from=/backup/$BACKUP_DATABASE --force --verbose && chown -R neo4j:neo4j /data/"
      volumeMounts:
      - name: backupdir
        mountPath: /backup
      - name: datadir
        mountPath: /data
  volumes:
  - name: backupdir
    persistentVolumeClaim:
      claimName: backupdir-graphdb-neo4j-core-0
  - name: datadir
    persistentVolumeClaim:
      claimName: datadir-graphdb-neo4j-core-0
---
